### ISSUE TITLE
Error: read /etc/ssl/influxdb-selfsigned.crt: is a directory

### ISSUE THREAD

**Issue by JamesYangLim** [Anaisdg/InfluxDBv2_Telegraf_Docker#1]
Hi,

I cloned and ran ```docker-compose up -d```. In influxdb_cli log, I am getting error "Failed to load x509 key pair" due to /etc/ssl/influxdb-selfsigned.crt is a directory. 

Any ideas how to solve this?

Thank you.

**Comment by VirtueMe** [comment]
@JamesYangLim  You need to create the certs your self. But I guess you figured that out your self.
