### ISSUE TITLE
Initial InfluxDB bucket name not used - org name used instead in entrypoint.sh

### ISSUE THREAD

**Issue by aughera** [Anaisdg/InfluxDBv2_Telegraf_Docker#3]
The initial InfluxDB setup is done in `entrypoint.sh`.

It currently says `influx setup --skip-verify --bucket ${DOCKER_INFLUXDB_INIT_ORG}` which is...suspicious.

I think that this _**should**_ be `influx setup --skip-verify --bucket ${DOCKER_INFLUXDB_INIT_BUCKET}`, and that until this is fixed the org name will be used for both the org name _and_ the bucket name.

**Comment by aughera** [comment]
I think that most people will use the same name for the org and the bucket, and not even notice it.

**Comment by Anaisdg** [comment]
Thank you
